<?php
    $css = $block->getAssetUrl('Dev_Widget::css/product-style.css');
    if($css)
    {
        echo '<link href="'.$css.'" rel="stylesheet" type="text/css" media="all" />';
    }
?>
    <div class="show-product-widget">
        <?php
        
            $sku = $block->getData('sku');
            $array = explode(",",$sku);
            foreach($array as $value)
            {
                
                $exist = $block->productExistBySku($value);
                $_product = $block->getProductBySku($value);
                $productUrl = $_product->getProductUrl();
                $imgPath = $_product->getData('image');
                $getUrl = $block->getUrl('media/catalog/product');
                $productName = $_product->getName();
                $productPrice = $_product->getFormattedPrice();      
                    
        ?>
        <div>
            <a class="product-link" href="<?php echo $productUrl; ?>">
                <img src="<?php echo $getUrl.$imgPath;?>" alt="NoImage" width="100%" />
            </a>
            <a class="product-link" href="<?php echo $productUrl; ?>">
                <p><?php echo $productName; ?></p>
            </a>       
            <span class="product-price-label">As low as</span>
            <span class="product-price"><?php echo $productPrice; ?></span>
        </div>
        <?php
            }
        ?>
    </div>

<!-- <script>
    require(['jquery', 'jquery/ui', 'slick'], function($) {
    $(document).ready(function() {
        $(".widget").slick({
            dots: true,
            infinite: false,
            slidesToShow: 5,
            slidesToScroll: 1,
            infinite: true,
        });
    });
});
</script> -->

<script>
    require([
        'jquery',
        'slick'
    ], function ($) {
        jQuery(document).ready(function () {
            jQuery(".show-product-widget").slick({
                dots: true,
                infinite: true,
                speed: 300,
                slidesToShow: 5,
                slidesToScroll: 4,
                responsive: [
                    {
                        breakpoint: 1280,
                        settings: {
                            slidesToShow: 3,
                            slidesToScroll: 3
                        }
                    },
                    {
                        breakpoint: 768,
                        settings: {
                            slidesToShow: 2,
                            slidesToScroll: 2
                        }
                    },
                    {
                        breakpoint: 600,
                        settings: {
                            slidesToShow: 1,
                            slidesToScroll: 1
                        }
                    }
                ]
            });
        });
    });
</script>